### ISSUE TITLE
Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate (default-cli) on project common-core: Execution default-cli of goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate failed: Cannot instantiate object of type com.github.dcendents.mybatis.generator.plugin.rename.RenameExampleClassAndMethodsPlugin 

### ISSUE THREAD

**Issue by MisterChangRay** [dcendents/mybatis-generator-plugins#2]
D:\ProgramsForDev\java8\bin\java "-Dmaven.home=D:\ProgramsForDev\IntelliJ IDEA 14.1.4\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\ProgramsForDev\IntelliJ IDEA 14.1.4\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=D:\ProgramsForDev\IntelliJ IDEA 14.1.4\bin" -Dfile.encoding=UTF-8 -classpath "D:\ProgramsForDev\IntelliJ IDEA 14.1.4\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;D:\ProgramsForDev\IntelliJ IDEA 14.1.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.4 org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building common-core Maven Webapp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- mybatis-generator-maven-plugin:1.3.5:generate (default-cli) @ common-core ---
[INFO] Connecting to the Database
[INFO] Introspecting table user
[INFO] Introspecting table role
[INFO] Introspecting table permission
[INFO] Introspecting table role_permission_map
[INFO] Introspecting table user_role_map
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.128s
[INFO] Finished at: Mon Mar 26 19:11:57 CST 2018
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate (default-cli) on project common-core: Execution default-cli of goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate failed: Cannot instantiate object of type com.github.dcendents.mybatis.generator.plugin.rename.RenameExampleClassAndMethodsPlugin -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

**Comment by dcendents** [comment]
The dependency must be added to the dependencies of mybatis-generator-maven-plugin and not as a project dependency.

e.g.:

```xml
<plugin>
	<groupId>org.mybatis.generator</groupId>
	<artifactId>mybatis-generator-maven-plugin</artifactId>
	<version>1.3.2</version>
	<configuration>
		<configurationFile>${basedir}/src/main/db/generatorConfig.xml</configurationFile>
		<overwrite>true</overwrite>
		<verbose>true</verbose>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>com.github.dcendents</groupId>
			<artifactId>mybatis-generator-plugins</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4-1201-jdbc41</version>
		</dependency>
	</dependencies>
</plugin>
```

**Comment by MisterChangRay** [comment]
thanks a million

**Comment by ipanocloud** [comment]
[ERROR] Failed to execute goal com.freetmp:xmbg-maven-plugin:1.1.1-SNAPSHOT:generate (default-cli) on project infosystem-server-config: Execution default-cli of goal com.freetmp:xmbg-maven-plugin:1.1.1-SNAPSHOT:generate failed: org.postgresql.util.PSQLException: ERROR: syntax error at or near "table"
???????????

**Comment by dcendents** [comment]
@ipanocloud it seems you are using and having an error from the xmbg-maven-plugin, this is not my plugin and can't help you with that.

**Comment by ipanocloud** [comment]
> @ipanocloud it seems you are using and having an error from the xmbg-maven-plugin, this is not my plugin and can't help you with that.

sorry
