### ISSUE TITLE
Implementing mybatis-generator-plugins

### ISSUE THREAD

**Issue by larocheaj** [dcendents/mybatis-generator-plugins#3]
The way I am implementing "Mybatis-generator-core" Version 1.3.7", is via an executable Jar file that is saved locally and works in conjunction to the config file that it needs. I tried implementing this project, or, "Mybatis-generator-plugins" in the same fashion. However, I  received the error "no main manifest attribute, in C:\Users\location\of\jarfile.jar" 

Daniel, I know you mentioned adding the Mybatis-generator-plugins dependency to the Mybatis-generator-mavin-plugin in my project's pom but unfortunately (given the implementation of the jar file, I haven't needed to include the Mybatis-generator-mavin-plugin). Is there a way I can implement your project in the same way? Via bundling it into an executable Jar and calling it via the commandline?

**Comment by dcendents** [comment]
If I understand correctly you want to run the mybatis-generator from the prompt as described here: http://www.mybatis.org/generator/running/runningFromCmdLine.html

This is not something I have tried, but I guess all you need is make sure my library is included in the classpath,

So something like: `java -cp mybatis-generator-plugins-1.3.jar -jar mybatis-generator-core-1.3.7.jar -configfile mbgConfig.xml -overwrite`

**Comment by larocheaj** [comment]
I believe you're correct here! So, I implemented a similar command to the one you just typed, I just used the literal path to both the files to get it working for the most part. By most part, I mean that without adding any plug in code from this project, the command executes fine with both files being referenced. However, when I included this plugin line to my mbgconfig.xml file:

 

> <plugin type="com.github.dcendents.mybatis.generator.plugin.subpackage.CreateSubPackagePlugin">
>             <property name="modelClassSuffix" value="Gen" />
>             <property name="mapperSubPackage" value="gen" />
>         </plugin>

 I got this error after running the command again:

> 
> Exception in thread "main" java.lang.RuntimeException: Cannot instantiate object of type com.github.dcendents.mybatis.generator.plugin.subpackage.CreateSubPackagePlugin
>         at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:182)
>         at org.mybatis.generator.internal.ObjectFactory.createPlugin(ObjectFactory.java:219)
>         at org.mybatis.generator.config.Context.generateFiles(Context.java:500)
>         at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269)
>         at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:189)
>         at org.mybatis.generator.api.ShellRunner.main(ShellRunner.java:117)
> Caused by: java.lang.ClassNotFoundException: com.github.dcendents.mybatis.generator.plugin.subpackage.CreateSubPackagePlugin
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:148)
>         at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:178)
>         ... 5 more
> 
> 

I'm assuming since the command executed with both files worked (without implementing any of this project's code) that we're now able to access the jar file of your project but my implementation of the plugin was done incorrectly in the config.xml?

**Comment by dcendents** [comment]
It cannot load the plugin class: ` java.lang.ClassNotFoundException: com.github.dcendents.mybatis.generator.plugin.subpackage.CreateSubPackagePlugin`

which means the jar file is not on the classpath.

Apparently it is not possible to use both `-jar` and `-cp` flags together. You need to invoke it differently:
`java -cp C:\path\to\mybatis-generator-core-1.3.7.jar;C:\path\to\mybatis-generator-plugins-1.3.jar org.mybatis.generator.api.ShellRunner -configfile mbgConfig.xml -overwrite`

**Comment by larocheaj** [comment]
Ahh I see. I tried using "java -cp C:\path\to\mybatis-generator-core-1.3.7.jar;C:\path\to\mybatis-generator-plugins-1.3.jar org.mybatis.generator.api.ShellRunner -configfile mbgConfig.xml -overwrite" and got this error:

> Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
>         at com.github.dcendents.mybatis.generator.plugin.subpackage.CreateSubPackagePlugin.<clinit>(CreateSubPackagePlugin.java:23)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:142)
>         at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:178)
>         at org.mybatis.generator.internal.ObjectFactory.createPlugin(ObjectFactory.java:219)
>         at org.mybatis.generator.config.Context.generateFiles(Context.java:500)
>         at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269)
>         at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:189)
>         at org.mybatis.generator.api.ShellRunner.main(ShellRunner.java:117)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 10 more

I double checked the paths to each of these jar files (they're in the same place) and they seem to be correct.

**Comment by dcendents** [comment]
It might be easier to use maven, even if it is just to run the mybatis-generator and not to build your project. Maven will handle transitive dependencies, otherwise that's something that you need to do manually. Fetch each dependent jar file, along with the jar files they depend on, and add all of them to the classpath.

Specifically you need to include *at least*

```xml
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.25</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.7</version>
		</dependency>
```
