### ISSUE TITLE
Param in Mapper class not change after use RenameExampleClassAndMethodsPlugin

### ISSUE THREAD

**Issue by Blackkee911** [dcendents/mybatis-generator-plugins#5]
Due to I have use RenameExampleClassAndMethodsPlugin for change generated class to be XXX. But @Param name of updateByXXX and updateByXXXSelective method in generated mapper class still show @Param("example"). Can this plugin change this param to be @Param("xxx") ? Thank you very much. This is my generatorConfig.xml code.

```
<plugin type="com.github.dcendents.mybatis.generator.plugin.rename.RenameExampleClassAndMethodsPlugin">
	<property name="classMethodSearchString" value="Example" />
	<property name="classMethodReplaceString" value="XXX" />
	<property name="parameterSearchString" value="example" />
	<property name="parameterReplaceString" value="xxx" />
</plugin>
```

**Comment by dcendents** [comment]
Hi @Blackkee911 , sorry for the late reply

Do you have a public project I can clone to reproduce the issue?
Or could you share your configuration file?

Also is it the same project as in #6 

Thanks
