### ISSUE TITLE
Update statement not add to Mapper.xml when use OptimisticLockingPlugin

### ISSUE THREAD

**Issue by Blackkee911** [dcendents/mybatis-generator-plugins#6]
I have add OptimisticLockingPlugin to generate updateByPrimaryKeyWithOptimisticLocking method in Mapper.java but when I try to run program I found updateByPrimaryKeyWithOptimisticLocking not exist in Mapper.xml. How can I fix it ? (before generate I have already delete old generated file and re-run command to generate again)

**Comment by jakalaka** [comment]
Same issue here.....
